# Generated by Django 3.2.3 on 2021-05-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210518_2304'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userfollowingrelation',
            table='user_following_relation',
        ),
    ]
