# Generated by Django 3.2.3 on 2021-05-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userfollowingrelation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='followes', to='user.User'),
        ),
        migrations.DeleteModel(
            name='UserFollowingRelation',
        ),
    ]
